export const membershipTypes = [
  'Diamond Card',
  'Gold Card Individual',
  'Gold Card Corporate',
  'New Gold Card Individual',
  'New Gold Card Corporate',
  'Life Membership Individual',
  'Life Membership Corporate',
  'Green Card',
  'Old Silver Card',
  'Privilege Gold Card',
  'Ordinary Members',
  'Honorary Member',
]

export const members = [
  {
    id: '1',
    full_name: 'Aarav Mehta',
    membership_type: 'Diamond Card',
    address: 'Palm Vista Villa, Agra',
    email: 'aarav@azurecrest.com',
    phone_number: '9876543210',
    membership_start_date: '2026-01-10',
    membership_end_date: '2026-12-31',
    valid_till: '2026-12-31',
    lifetime_status: false,
    payment_status: 'Paid',
    amount_paid: 240000,
    total_amount: 240000,
    due_amount: 0,
    renewal_date: '2026-12-01',
    notes: 'Prefers golf access and concierge updates.',
    is_active: true,
    created_at: '2026-01-10',
  },
  {
    id: '2',
    full_name: 'Riya Khanna',
    membership_type: 'Gold Card Individual',
    address: 'Lakefront Residency, Delhi',
    email: 'riya.khanna@email.com',
    phone_number: '9876501234',
    membership_start_date: '2025-09-15',
    membership_end_date: '2026-09-14',
    valid_till: '2026-09-14',
    lifetime_status: false,
    payment_status: 'Partial',
    amount_paid: 65000,
    total_amount: 90000,
    due_amount: 25000,
    renewal_date: '2026-08-25',
    notes: 'Corporate guest approvals pending.',
    is_active: true,
    created_at: '2025-09-15',
  },
  {
    id: '3',
    full_name: 'Viren Hospitality Pvt Ltd',
    membership_type: 'Gold Card Corporate',
    address: 'Cyber Greens, Gurugram',
    email: 'accounts@virenhospitality.in',
    phone_number: '9811102200',
    membership_start_date: '2024-04-01',
    membership_end_date: '2026-06-20',
    valid_till: '2026-06-20',
    lifetime_status: false,
    payment_status: 'Pending',
    amount_paid: 120000,
    total_amount: 200000,
    due_amount: 80000,
    renewal_date: '2026-06-15',
    notes: 'High-value corporate bundle.',
    is_active: true,
    created_at: '2024-04-01',
  },
  {
    id: '4',
    full_name: 'Maya Suri',
    membership_type: 'Life Membership Individual',
    address: 'Royal Orchard, Jaipur',
    email: 'maya@royalorchard.in',
    phone_number: '9988776655',
    membership_start_date: '2023-03-08',
    membership_end_date: null,
    valid_till: null,
    lifetime_status: true,
    payment_status: 'Lifetime',
    amount_paid: 500000,
    total_amount: 500000,
    due_amount: 0,
    renewal_date: null,
    notes: 'Founding member.',
    is_active: true,
    created_at: '2023-03-08',
  },
  {
    id: '5',
    full_name: 'Kabir Anand',
    membership_type: 'Green Card',
    address: 'Riverview Enclave, Noida',
    email: 'kabir.anand@email.com',
    phone_number: '9123456780',
    membership_start_date: '2025-02-11',
    membership_end_date: '2026-05-30',
    valid_till: '2026-05-30',
    lifetime_status: false,
    payment_status: 'Pending',
    amount_paid: 15000,
    total_amount: 45000,
    due_amount: 30000,
    renewal_date: '2026-05-10',
    notes: 'Membership expired last week.',
    is_active: false,
    created_at: '2025-02-11',
  },
]

export const payments = [
  { id: 'p1', member_id: '1', amount: 240000, status: 'Paid', paid_on: '2026-01-10', method: 'Bank Transfer', notes: 'Annual membership cleared.' },
  { id: 'p2', member_id: '2', amount: 65000, status: 'Partial', paid_on: '2026-02-20', method: 'Card', notes: 'Initial installment.' },
  { id: 'p3', member_id: '3', amount: 120000, status: 'Pending', paid_on: null, method: 'Invoice', notes: 'Awaiting corporate approval.' },
  { id: 'p4', member_id: '4', amount: 500000, status: 'Lifetime', paid_on: '2023-03-08', method: 'Wire', notes: 'Lifetime privilege access.' },
  { id: 'p5', member_id: '5', amount: 15000, status: 'Pending', paid_on: '2025-02-12', method: 'Cash', notes: 'Balance overdue.' },
]

export const activities = [
  { id: 'a1', action: 'Member imported from CSV', actor: 'Admin', created_at: '2026-06-04T09:15:00' },
  { id: 'a2', action: 'Payment marked as partial', actor: 'Finance Desk', created_at: '2026-06-04T12:25:00' },
  { id: 'a3', action: 'Membership renewal alert issued', actor: 'System', created_at: '2026-06-05T07:10:00' },
]